export enum AddonPrefix {
  GOAL_CLAIM = "NIKEV_GOAL_CLAIM",
  GOAL_ITEM = "NIKEV_GOAL_ITEM",
  GOAL_READY = "NIKEV_GOAL_READY",
  SPECS_LIST = "NIKEV_SPECS",
  SPECS_READY = "NIKEV_SPEC_RDY",
  SWITCH_SPEC = "SWITCH_SPEC",
  SPEC_BAR_LOAD = "SPEC_BAR_LOAD",
  SPEC_BAR_SLOT = "SPEC_BAR_SLOT",
  SPEC_BAR_DONE = "SPEC_BAR_DONE",
}
